author: muffinjello
description: Let's you change the MOTD of your plugin easily.
main: me.muffinjello.pluginflow.motdflow.Motdflow
name: MOTDflow
startup: postworld
url: http://www.shortcutminecraft.com/
version: '0.1'
commands:
    +motd:
        description: Change your server's MOTD
        usage: /motd <MOTD>